const fieldLabels: Record<string, string> = {
  ITEM_SEQ: '품목기준코드',
  ITEM_NAME: '품목명',
  ENTP_NAME: '업체명',
  ITEM_PERMIT_DATE: '허가일자',
  CNSGN_MANUF: '위탁제조업체',
  ETC_OTC_CODE: '전문일반',
  CHART: '성상',
  BAR_CODE: '표준코드',
  MATERIAL_NAME: '원료성분',
  EE_DOC_ID: '효능효과',
  UD_DOC_ID: '용법용량',
  NB_DOC_ID: '주의사항',
  INSERT_FILE: '첨부문서',
  STORAGE_METHOD: '저장방법',
  VALID_TERM: '유효기간',
  REEXAM_TARGET: '재심사대상',
  REEXAM_DATE: '재심사기간',
  PACK_UNIT: '포장단위',
  EDI_CODE: '보험코드',
  PERMIT_KIND_NAME: '허가/신고구분',
  ENTP_NO: '업체허가번호',
  MAKE_MATERIAL_FLAG: '완제/원료구분',
  NEWDRUG_CLASS_NAME: '신약',
  INDUTY_TYPE: '업종구분',
  CANCEL_DATE: '취소일자',
  CANCEL_NAME: '상태',
  CHANGE_DATE: '변경일자',
  NARCOTIC_KIND_CODE: '마약종류코드',
  GBN_NAME: '변경이력',
  TOTAL_CONTENT: '총량',
  EE_DOC_DATA: '효능효과 문서 데이터',
  UD_DOC_DATA: '용법용량 문서 데이터',
  NB_DOC_DATA: '주의사항(일반) 문서 데이터',
  PN_DOC_DATA: '주의사항(전문) 문서 데이터',
  MAIN_ITEM_INGR: '유효성분',
  INGR_NAME: '첨가제',
  ATC_CODE: 'ATC코드',
  ITEM_ENG_NAME: '품목영문명',
  ENTP_ENG_NAME: '업체영문명',
  MAIN_INGR_ENG: '주성분영문명',
  BIZRNO: '사업자등록번호',
  RARE_DRUG_YN: '희귀의약품여부',
};

export default fieldLabels;
